[2022-09-08T10:32:07.544+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-04T00:00:00+00:00 [queued]>
[2022-09-08T10:32:07.647+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-04T00:00:00+00:00 [queued]>
[2022-09-08T10:32:07.659+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:07.661+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:32:07.664+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:08.040+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2021-08-04 00:00:00+00:00
[2022-09-08T10:32:08.201+0000] {standard_task_runner.py:52} INFO - Started process 3354 to run task
[2022-09-08T10:32:08.322+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-04T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmpahz1rgl8', '--error-file', '/tmp/tmp6x123lkd']
[2022-09-08T10:32:08.355+0000] {standard_task_runner.py:80} INFO - Job 38: Subtask second_task
[2022-09-08T10:32:09.192+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-04T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:32:17.509+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T00:00:00+00:00
[2022-09-08T10:32:17.534+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:32:17.543+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-09-08T10:32:17.719+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:32:17.724+0000] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-09-08T10:32:17.736+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-08T10:32:18.011+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210804T000000, start_date=20220908T103207, end_date=20220908T103218
[2022-09-08T10:32:18.785+0000] {local_task_job.py:227} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-08T10:32:18.812+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3354. PIDs of all processes in the group: [3354]
[2022-09-08T10:32:18.815+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3354
[2022-09-08T10:32:18.817+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=3354, status='terminated', exitcode=0, started='10:32:07') (3354) terminated with exit code 0
